config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get :app, to: 'static_pages#app'

  namespace :api do
    resources :activities, only: :index
    resources :babies, only: :index do
      get :activity_logs
    end
    resources :activity_logs, only: %i[create update]
  end
  resources :activity_logs, only: :index
end

app/models/activity.rb
# frozen_string_literal: true

# Activity
class Activity < ApplicationRecord
  validates :name, :description, presence: true
  has_many :activity_logs

  def self.to_response
    order(:created_at).select(:id, :name, :description)
  end
end

app/models/activity_log.rb
# frozen_string_literal: true

# Activity Log
class ActivityLog < ApplicationRecord
  belongs_to :baby
  belongs_to :assistant
  belongs_to :activity

  validates :start_time, presence: true
  validate :stop_time_must_be_bigger, on: :update
  before_create :init_status
  before_update :update_duration

  enum status: %i[started finished]

  def stop_time_must_be_bigger
    return unless stop_time < start_time

    errors.add(:stop_time, 'stop time must be bigger than start time')
  end

  private

  def update_duration
    self.duration = (stop_time - start_time) / 60
    self.status = :finished
  end

  def init_status
    self.status = stop_time ? :finished : :started
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistant.rb
# frozen_string_literal: true

# Assistant
class Assistant < ApplicationRecord
  validates :name, presence: true
  has_many :activity_logs
end

app/models/baby.rb
# frozen_string_literal: true

# Baby
class Baby < ApplicationRecord
  validates :name, :birthday, :mother_name, presence: true
  has_many :activity_logs

  def self.to_response
    order(:created_at).map do |baby|
      { id: baby.id, name: baby.name, months: baby.months,
        mother_name: baby.mother_name, father_name: baby.father_name,
        address: baby.address, phone: baby.phone }
    end
  end

  def activity_logs
    super.order(:created_at).map do |activity_log|
      {
        id: activity_log.id,
        baby_id: activity_log.baby_id,
        assistant_name: activity_log.assistant.name,
        start_time: activity_log.start_time,
        stop_time: activity_log.stop_time
      }
    end
  end

  def months
    date1 = Time.now
    date2 = birthday
    (date1.year - date2.year) * 12 + \
      date1.month - date2.month - \
      (date1.day >= date2.day ? 0 : 1)
  end
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activity_logs_controller.rb
# frozen_string_literal: true

# Activity Logs Controller
class ActivityLogsController < ApplicationController
  before_action :authenticate_user!

  def index
    set_activities
    return paginated unless params['activity_log']

    search_baby
    search_assistant
    search_status

    paginated
  end

  private

  def set_activities
    @activity_logs = ActivityLog.order(:start_time)
  end

  def search_baby
    return if object_params['baby_id'].nil?
    return if object_params['baby_id'].empty?

    @activity_logs = @activity_logs.where(baby_id: object_params['baby_id'])
  end

  def search_assistant
    return if object_params['assistant_id'].nil?
    return if object_params['assistant_id'].empty?

    @activity_logs =
      @activity_logs.where(assistant_id: object_params['assistant_id'])
  end

  def search_status
    return if object_params['status'].nil?
    return if object_params['status'].empty?

    @activity_logs = @activity_logs.where(status: object_params['status'])
  end

  def object_params
    params.require(:activity_log).permit(:baby_id, :assistant_id, :status)
  end

  def paginated
    @activity_logs = @activity_logs.paginate(page: params[:page])
  end
end

app/controllers/api/activities_controller.rb
# frozen_string_literal: true

module Api
  # Activities Controller
  class ActivitiesController < ApplicationController
    def index
      render json: Activity.to_response, status: :ok
    end
  end
end

app/controllers/api/activity_logs_controller.rb
# frozen_string_literal: true

module Api
  # Activity Logs Controller
  class ActivityLogsController < ApplicationController
    protect_from_forgery

    def create
      @activity_log = ActivityLog.new create_params
      if @activity_log.save
        render json: @activity_log, status: :ok
      else
        render json: { errors: @activity_log.errors },
               status: :unprocessable_entity
      end
    end

    def update
      find_activity_log
      return unless valid_date?

      if @activity_log.update update_params
        render json: @activity_log, status: :ok
      else
        render json: { errors: @activity_log.errors },
               status: :unprocessable_entity
      end
    end

    private

    def valid_date?
      return true unless update_params[:stop_time].empty?

      render json: { errors: { stop_time: 'Not valid date' } },
             status: :unprocessable_entity
      false
    end

    def find_activity_log
      @activity_log = ActivityLog.find(params[:id])
      return if @activity_log

      render json: { errors: 'Not found' }, status: :not_found
    end

    def create_params
      params.require(:activity_log).permit(:activity_id,
                                           :baby_id,
                                           :assistant_id,
                                           :start_time)
    end

    def update_params
      params.require(:activity_log).permit(:id, :stop_time, :comments)
    end
  end
end

app/controllers/api/babies_controller.rb
# frozen_string_literal: true

module Api
  # Babies Controller
  class BabiesController < ApplicationController
    def index
      render json: Baby.to_response, status: :ok
    end

    def activity_logs
      find_baby
      render json: @baby.activity_logs, status: :ok
    end

    private

    def find_baby
      @baby = Baby.find(params[:baby_id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  def render_404
    render json: { error: 'Not found', status: :not_found }, status: :not_found
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# Static Pages Controller
class StaticPagesController < ApplicationController
  def home; end

  def app; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

# Static Pages Helper
module StaticPagesHelper
end

app/views/activity_logs/index.slim
h3 = ActivityLog.model_name.human

= simple_form_for(:activity_log, url: activity_logs_url, method: :get) do |f|
  .row
    .col-3
      = f.input :baby_id, label: t(:baby_id), collection: Baby.all
    .col-3
      = f.input :assistant_id, label: t(:assistant_id), collection: Assistant.all
    .col-3
      = f.input :status, label: t(:status), collection: [:started, :finished]
    .col-3
      = f.submit :search, label: t(:search), class: 'btn btn-info'

table.table.mt-3
  thead.thead-dark
    tr
      th = Baby.model_name.human
      th = Assistant.model_name.human
      th = Activity.model_name.human
      th = ActivityLog.human_attribute_name(:start_time)
      th = ActivityLog.human_attribute_name(:status)
      th = ActivityLog.human_attribute_name(:duration)
  tbody
    - @activity_logs.each do |activity_log|
      tr
        td = activity_log.baby.name
        td = activity_log.assistant.name
        td = activity_log.activity.name
        td = activity_log.start_time
        td = t("activity_log_status.#{activity_log.status}")
        td = activity_log.duration

= will_paginate @activity_logs, class: 'digg_pagination'

javascript:
  $('select').selectize();

app/views/layouts/application.slim
DOCTYPE
html
  head
    title KineduTest
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/partials/navbar'
    .container.mt-5
      .row
        .col
          - if alert
              .alert.alert-danger.alert-dismissible.fade.show role="alert"
                strong.notice = alert

                button type="button" class="close" data-dismiss="alert" aria-label="Close"
                  span aria-hidden="true" &times;

          - if notice
              .alert.alert-success.alert-dismissible.fade.show role="alert"
                strong.notice = notice

                button type="button" class="close" data-dismiss="alert" aria-label="Close"
                  span aria-hidden="true" &times;

          = yield

app/views/layouts/partials/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    = link_to 'KineduTest', root_path, class: 'navbar-brand'
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon

    div#navbarSupportedContent.collapse.navbar-collapse
      .mr-auto

      - unless user_signed_in?
        ul.navbar-nav
          li.nav-item
            = link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link'
        ul.navbar-nav
          li.nav-item
            = link_to 'Regístrate', new_user_registration_path, class: 'nav-link'
      - else
        ul.navbar-nav
          li.nav-item
            = link_to ActivityLog.model_name.human, activity_logs_path, class: 'nav-link'
          li.nav-item
            = link_to 'Cerrar Sesión', destroy_user_session_path, class: 'nav-link', method: :delete

app/views/static_pages/app.slim
h1 StaticPages#app
p Find me in app/views/static_pages/app.html.erb

app/views/static_pages/home.slim
h2 = t(:welcome)